### ISSUE TITLE
Package.swift manifest is missing in 3.0.0

### ISSUE THREAD

**Issue by SentoCrespo** [tbaranes/VersionTrackerSwift#26] opened 2021-02-03 13:30 UTC
Hi! 

I'm reporting the issue I'm having when trying to migrate from CocoaPods to Swift Package Manager (SPM). When I try to fetch the repository, with the latest version (3.0.0) I get this error:

`https://github.com/tbaranes/VersionTrackerSwift has no Package.swift manifest for version 3.0.0`

Also, this happens when trying to fetch this repository by that exact version.

In case it helps, I'm using Xcode 12.4 and the rest of my dependencies work just fine with SPM.

Thanks for your work!

**Comment by thislooksfun** [comment] 2021-12-11 21:03
@tbaranes this is caused by the `3.0.0` release having been tagged before #23 was merged. Can you please tag a new release (`3.0.1` would be fine) so we can use it directly?

@vCrespoP in the meantime you can manually target `fedea0c30fd804023868f4f7ff288fd4bba8aa97` instead of `3.0.0`

**Comment by tbaranes** [comment] 2021-12-12 11:49
Thanks for pinging me, I missed that notification. I created a 3.0.1 tag so you can use it directly. Sorry for the delay! 

Let me know if there's anything else

**Closed as completed** 2021-12-12 11:49 UTC
